export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Project

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";


//BACKLOG


export const GET_BACKLOG = "GET_BACKLOG";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";


//Tenant


export const GET_TENANT = "GET_TENANT";
export const GET_TENANTS = "GET_TENANTS";
export const DELETE_TENANT= "DELETE_TENANT";


export const GET_AUTOMAT = "GET_AUTOMAT";
export const GET_AUTOMATS = "GET_AUTOMATS";
export const DELETE_AUTOMAT= "DELETE_AUTOMAT";


export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT= "DELETE_PRODUCT";



export const GET_PRODUCT_TO_AUTOMAT = "GET_PRODUCT_TO_AUTOMAT";
export const GET_PRODUCT_TO_AUTOMATS = "GET_PRODUCT_TO_AUTOMATS";
export const DELETE_PRODUCT_TO_AUTOMAT= "DELETE_PRODUCT_TO_AUTOMAT";

export const GET_FUNDS_DRAWN = "GET_FUNDS_DRAWN";
export const GET_FUNDS_DRAWNS = "GET_FUNDS_DRAWNS";
export const DELETE_FUNDS_DRAWN = "DELETE_FUNDS_DRAWN";


export const GET_INSERTED_PRODUCT = "GET_INSERTED_PRODUCT";
export const GET_INSERTED_PRODUCTS = "GET_INSERTED_PRODUCTS";
export const DELETE_INSERTED_PRODUCT = "DELETE_INSERTED_PRODUCT";

export const GET_PURCHASED_PRODUCT = "GET_PURCHASED_PRODUCT";
export const GET_PURCHASED_PRODUCTS = "GET_PURCHASED_PRODUCTS";
export const DELETE_PURCHASED_PRODUCT = "DELETE_PURCHASED_PRODUCT";